/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        vsc: {
          bg: '#0A0A0D',
          sidebar: '#0E0E12',
          panel: '#131318',
          hover: '#1A1A22',
          active: '#20202A',
          border: '#28283A',
          text: '#EEEEF0',
          muted: '#8888A0',
          dim: '#48485C',
          accent: '#6366F1',
          'accent-light': 'rgba(99,102,241,0.10)',
          'accent-hover': '#4F52D3',
          danger: '#F87171',
          'danger-light': 'rgba(248,113,113,0.10)',
          success: '#34D399',
          warning: '#FBBF24',
          blue: '#60A5FA',
          code: '#07070B',
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'Consolas', 'monospace'],
      },
      borderRadius: {
        none: '0',
        sm: '3px',
        DEFAULT: '5px',
        md: '7px',
        lg: '10px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs: ['11px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '20px' }],
        base: ['14px', { lineHeight: '22px' }],
        lg: ['16px', { lineHeight: '24px' }],
        xl: ['18px', { lineHeight: '28px' }],
        '2xl': ['22px', { lineHeight: '32px' }],
        '3xl': ['28px', { lineHeight: '36px' }],
      },
    },
  },
  plugins: [],
}
